In [69]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files

In [70]:
#data Inseting Manually

In [71]:
import pandas as pd

data = pd.DataFrame({
    'emp_id': [101,102,103,104,105,106,107,108,109,110],
    'name': ['Arjun','Ravi','Priya','Amit','Neha','Kiran','Sneha','Raj','Pooja','Vikas'],
    'department': ['Sales','sales','HR','hr','IT','it','Software','software','Support','support'],
    'salary': [50000,60000,None,45000,70000,None,80000,75000,40000,None],
    'experience': [2,5,3,1,6,4,7,5,2,3],
    'city': ['Mumbai','Pune','Mumbai','Delhi','Pune','Mumbai','Delhi','Pune','Mumbai','Delhi']
})

data

   emp_id   name department   salary  experience    city
0     101  Arjun      Sales  50000.0           2  Mumbai
1     102   Ravi      sales  60000.0           5    Pune
2     103  Priya         HR      NaN           3  Mumbai
3     104   Amit         hr  45000.0           1   Delhi
4     105   Neha         IT  70000.0           6    Pune
5     106  Kiran         it      NaN           4  Mumbai
6     107  Sneha   Software  80000.0           7   Delhi
7     108    Raj   software  75000.0           5    Pune
8     109  Pooja    Support  40000.0           2  Mumbai
9     110  Vikas    support      NaN           3   Delhi

In [72]:
#🧹 TASK 1: Data Cleaning

In [73]:
data['department']=data['department'].str.replace(r'(?i)sales','Sales',regex=True)
data['department']=data['department'].str.replace(r'(?i)hr','HR',regex=True)
data['department']=data['department'].str.replace(r'(?i)support','Support',regex=True)
data['department']=data['department'].str.replace(r'(?i)IT','IT',regex=True)
data['department']=data['department'].str.replace(r'(?i)Software','Software',regex=True)
data

   emp_id   name department   salary  experience    city
0     101  Arjun      Sales  50000.0           2  Mumbai
1     102   Ravi      Sales  60000.0           5    Pune
2     103  Priya         HR      NaN           3  Mumbai
3     104   Amit         HR  45000.0           1   Delhi
4     105   Neha         IT  70000.0           6    Pune
5     106  Kiran         IT      NaN           4  Mumbai
6     107  Sneha   Software  80000.0           7   Delhi
7     108    Raj   Software  75000.0           5    Pune
8     109  Pooja    Support  40000.0           2  Mumbai
9     110  Vikas    Support      NaN           3   Delhi

In [74]:
#Fill missing salary with average salary

In [75]:

data['salary']=data['salary'].fillna(data['salary'].mean())

In [76]:
#Check data types

In [77]:
data.dtypes

emp_id          int64
name           object
department     object
salary        float64
experience      int64
city           object
dtype: object

📊 TASK 2: Data Analysis

In [78]:
#Average salary

In [79]:
data['salary'].mean()

np.float64(60000.0)

In [80]:
#Highest salary employee

In [81]:
data[['name','salary']].max()

name        Vikas
salary    80000.0
dtype: object

In [82]:
#Lowest salary employee

In [83]:
data[['name','salary']].min()

name         Amit
salary    40000.0
dtype: object

🔥 GroupBy Questions

In [84]:
#Department-wise average salary

In [85]:
data.groupby('department')['salary'].mean()

department
HR          52500.0
IT          65000.0
Sales       55000.0
Software    77500.0
Support     50000.0
Name: salary, dtype: float64

In [86]:
#City-wise employee count

In [87]:
data.groupby('city')['city'].count()

city
Delhi     3
Mumbai    4
Pune      3
Name: city, dtype: int64

In [88]:
#Department-wise total salary

In [89]:
data.groupby('department')['salary'].sum()

department
HR          105000.0
IT          130000.0
Sales       110000.0
Software    155000.0
Support     100000.0
Name: salary, dtype: float64

🔥 Advanced Filtering

In [90]:
#Employees with salary > 60000

In [91]:
a=data[data['salary']>60000][['name','salary']]

In [92]:
a

    name   salary
4   Neha  70000.0
6  Sneha  80000.0
7    Raj  75000.0

In [93]:
#Employees from Mumbai with experience > 3

In [94]:
data[data['experience']>3][['name','experience']]

    name  experience
1   Ravi           5
4   Neha           6
5  Kiran           4
6  Sneha           7
7    Raj           5

In [95]:
#Which department has highest salary?

In [96]:
data.groupby('department')['salary'].max().sort_values(ascending=False).head(1)

department
Software    80000.0
Name: salary, dtype: float64

In [97]:
  #Which city has more employees?

In [98]:
data.groupby('city')['city'].count().sort_values(ascending=False).head(1)

city
Mumbai    4
Name: city, dtype: int64

In [99]:
#Does experience affect salary?

In [100]:
data[['salary','experience']].corr()

            salary  experience
salary      1.0000      0.9061
experience  0.9061      1.0000

In [100]:
data.to_csv('employee_data.csv',index=False)
files.download('employee_data.csv')